### PR TITLE
Prepare data architecture documentation Milestone 1

### PR DESCRIPTION
**Pull request by pountzas**
# Add ERD.
- Users database table.
- Friendship database table.
- Posts database table.
- Comments database table.
- Likes database table.

### CODE REVIEW

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# STATUS: Changes Required :red_circle: 

## Hello @pountzas good job  so far, your ERD diagram looks almost complete

### To improve: 
- [ ] In your `Like` table change the _likable_id_ to _post_id_
- [ ] The relationship between the `USER` and `FRIENDSHIP` table should be as followng:
Screenshot from 2021-04-30 01-02-01
- [x] Add linters in your project

### If you have any question with regards to the requirements please add a comment here and I will try to reply ASAP.

# HAPPY CODING :computer: :desktop_computer:

**Comment by pountzas** [comment]
Likable_id is a polymorphic association.
https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails/lessons/active-record-associations#polymorphic-associations

This makes no sense. Your ERD seems wrong, the name is not unique and is not a key and the User can only have 1 status.

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coder, 👋🏽 
**This is a great project you have going on, well-done lad and thanks for implementing the changes requested earlier on**. 

### Well-done 💯 
    1. The ERD is almost complete, 👍🏽 

**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

### REQUIRED

- [x] Add the linter files to your repo.
- [ ] Here is what the association between the user and friendship should seem like. Just as the previous CR presented in the screenshot.
1. One Friendship is sent by only One User.
2. One User can send many Friendships.
3. One Friendship is received by only One User.
4. One User can receive many Friendships.



### OPTIONAL

- [x] Change all PKs to the standard format. The PK for Users is ID and not user_id. The latter is used as an FK in other tables to bring about the association between the two tables. Make the changes for all the PKs in all tables.
- [ ] Always ensure to follow and apply Github flow at all times in your project. Only compare the develop branch to the master while preparing for production otherwise, always compare the feature branch to the develop branch. 

#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Comment by rukundoeric** [comment]
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  - Implemented required changes. 💯 

- ### To Improve
  - [ ] [Mandatory] You did not follow Gitwork flow. which means you shouldn't have created a PR from the development branch(on this milestone) since it is supposed to be the default branch. to fix this, instead of merging this PR to main branch, close it and follow these simple steps to make development a default branch. and then on the next milestone create a new branch from the development branch.
     - Make development a default branch:
        - Go to settings 
        scrnli_6_4_2021_7-42-44 PM
        - Click on the branch
        scrnli_6_4_2021_7-43-56 PM
        - Click on this icon
        scrnli_6_4_2021_7-44-46 PM
        - And then finally, select development branch and then click on update.
        scrnli_6_4_2021_7-45-39 PM



        

_Congratulations on the splendid job **@team** 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/),
Slack: Rukundo Eric**

**Pull request closed without merging**
