### PR TITLE
Friendships v1

### PR DESCRIPTION
**Pull request by pountzas**
- create invitations table with associations to user
- create methods for invitation model
- add buttons to users and profile pages depending on the relation between user and current user

### CODE REVIEW

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED 🔴 🛑 
------------
Hello @pountzas,  great job you are doing on this milestone 👏 👍 
TO HIGHLIGHT: 

- Well structured files 
- Your repo is professional
- Your Project is professional
- Well use of the MPV
However, there is a minor change to make to complete this milestone 🛠️ see  below 👀 👇 
--------------

- [ ] Please add  Unit and Integration tests. 

tests

-------------
Make this required change and send it again for another review 💪 👍 
HAPPY CODING!!! 

36ab81cd8d63cf7c4a08f39403698c77

**Review by umararshadbut — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @pountzas 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes  👇.
- [ ] Please add the unit, integration tests, and negative tests for friendship. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**Umair**

**Comment by umararshadbut** [comment]
Hello @pountzas 
You can verify this requirement from Pathwright.
([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

Best,
Umair Arshad

**Comment by pountzas** [comment]
I have named Invitation and not Friendship for model and controller and I have implemented the unit, integration tests.

**Comment by rukundoeric** [comment]
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  - Follows gitwork-flow.  💯
  - Codebase looks clean and professinal. 💯 
  - Feedback implemented. 💯 

- ### To Improve
  - N/A

_Congratulations on the splendid job **@team** 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/),
Slack: Rukundo Eric**

**Pull request merged**
